#include <iostream>
using namespace std;


//class MyException : public exception { // base of all logic-error exceptions
//
//};
//
//
//void go(int a, int b)
//{
//	if (a < 0 || b < 0)
//		throw std::invalid_argument("음수 불가");
//	if (a > 10 || b > 10)
//		throw std::out_of_range("10 이하 인자 필요");
//	cout << a + b;
//}

int main()
{
	//try {
	//	go(1, 2);
	//	//go(11, -1);
	//}
	//catch (invalid_argument e)
	//{
	//	cout << e.what() << endl;

	//}
	//catch (out_of_range e)
	//{
	//	cout << e.what() << endl;
	//}
	//catch (...)
	//{
	//	cout << "Errors";
	//}
}